language: objective-c
osx_image:
  - xcode8
  - xcode7.3
  - xcode6.4
env:
  - SCHEME=TapstreamIOS SDK=iphonesimulator

script:
  - xctool test -workspace tapstream-sdk-ios.xcworkspace -scheme $SCHEME -sdk $SDK CODE_SIGNING_REQUIRED=NO
